language: node_js
node_js:
  - 'stable'

script:
  - yarn lint
  - yarn build --prod --aot --base-href https://groninge01.github.io/api-test/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/api-test
  on:
    branch: master
